### ISSUE TITLE
Scripts don't support "/.steam/compatibilitytools.d/compatibilitytool.vdf" variety of installation

### ISSUE THREAD

**Issue by redmcg** [redmcg/Proton#1]
Added to my TODO list

**Comment by sizeofbool** [comment]
I've modified your scripts, so they will work even if custom proton build folder is not inside "/compatibilitytools.d/" folder.
I assume users will modify "/compatibilitytool.vdf" manually if they want custom proton builds to be in external folders.
It's not perfect solution, but robust and gets the job done.
[fixed_scripts.tar.gz](https://github.com/redmcg/Proton/files/2694314/fixed_scripts.tar.gz)

**Comment by redmcg** [comment]
Thanks for this. I'm also going to change where vcrun2015 and dotnet are downloaded by default. I found a problem with the 'Steamworks Shared' location: If you have a game that uses this location through Steam and then uninstall it - Steam will delete this directory.

So I need to put it in a location that is not used by Steam. Probably under $HOME/.cache (like winetricks does).

**Comment by redmcg** [comment]
I just released [Proton 3.16-6 Beta - for Elite Dangerous](https://github.com/redmcg/wine/releases/tag/ED_Proton_3.16-6_Beta) and I tested this type of install and it works (due to virtue of not needing to know the Steam location with the new download location). But thanks for pointing this out - I hadn't tested it in previous releases. I'll close this but please do open it if you find an issue.
